resources:
- name: application
  type: git
  source:
    uri: https://github.com/gina-alaska/ubermap.git
    branch: concourse_build
- name: hab-ci 
  type: git
  source:
    uri: https://github.alaska.edu/gina/concourse-chef-test.git
    username: {{git-username}}
    password: {{git-password}} 
- name: gina-packages
  type: s3
  source:
    bucket: gina-packages
jobs:
- name: build-habitat-pkg
  public: true
  plan:
  - get: hab-ci
  - get: application
  - task: build
    privileged: true
    file: hab-ci/habitat/build.yml
    output:
      name: results
      path: /src/results
    params:
      PACKAGE_NAME: ubermap
      HABITAT_ORIGIN_KEY: {{habitat-origin-key}}
      HABITAT_ORIGIN_FILENAME: {{habitat-origin-filename}}
      HABITAT_ORIGIN_CONTENT: {{habitat-origin-content}}
      HABITAT_PUB_FILENAME: {{habitat-pub-filename}}
      HABITAT_PUB_CONTENT: {{habitat-pub-content}}
  - put: gina-packages
    params:
      file: /src/results/uafgina-ubermap-*.hart
