resources:
- name: application
  type: git
  source:
    uri: https://github.com/gina-alaska/ubermap.git
    branch: concourse_build

jobs:
- name: build-habitat-pkg
  public: true
  plan:
  - get: application
  - task: build
    privileged: true
    file: application/habitat/build.yml
    params:
      PACKAGE_NAME: ubermap
      HABITAT_ORIGIN_KEY: {{habitat-origin-key}}
      HABITAT_ORIGIN_FILENAME: {{habitat-origin-filename}}
      HABITAT_ORIGIN_CONTENT: {{habitat-origin-content}}
      HABITAT_PUB_FILENAME: {{habitat-pub-filename}}
      HABITAT_PUB_CONTENT: {{habitat-pub-content}}
