production:
  secret_key_base: {{cfg.secret_key_base}}
  bucket_name: {{cfg.ubermap_s3_bucket}}
  aws_access_key_id: {{ cfg.aws_secret_key_id }}
  aws_secret_access_key: {{ cfg.aws_secret_acces_key }}
