---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bscott/habitat

inputs:
- name: application

params:
  APPLICATION_PATH: application

run:
  path: ./application/habitat/concourse/build.sh
