name             'ubermap'
maintainer       'UAFGINA'
maintainer_email 'scott@gina.alaska.edu'
license          'All rights reserved'
description      'Installs/Configures ubermap'
long_description 'Installs/Configures ubermap'
version          '0.1.5'

depends 'yum-gina'
depends 'yum-epel'
depends 'nginx'
depends 'redisio'
depends 'chruby'
depends 'unicorn'
depends 'postgresql'
depends 'database'
depends "sudo"